[package]
name = "ministat"
version = "0.1.2"
authors = ["Mark Sherry <mdsherry@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
noisy_float = "0.2"
terminal_size = "0.1.7"
kahan = "0.1.0"
clap = { version = "3.1.18", features = ["derive"] }
